# Generated by Django 4.2.1 on 2023-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('produto_comercial', models.CharField(max_length=100)),
                ('alvo', models.CharField(max_length=100)),
                ('area_a_tratar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_da_calda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('intervalo_de_seguranca', models.IntegerField()),
                ('modalidade_aplicacao', models.CharField(max_length=100)),
                ('equipamento_aplicacao', models.CharField(max_length=100)),
                ('quantidade_a_adquirir', models.IntegerField()),
                ('n_aplicacoes', models.IntegerField()),
                ('epoca_aplicacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnostícos',
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('propriedade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Produtor rural',
                'verbose_name_plural': 'Produtores rurais',
                'db_table': 'produtor_rural',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14)),
                ('local', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'db_table': 'propriedade',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('numero_registro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Responsável técnico',
                'verbose_name_plural': 'Responsáveis técnicos',
                'db_table': 'responsal_tecnico',
            },
        ),
    ]
