# Generated by Django 4.2.1 on 2023-05-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='responsaveltecnico',
            table='responsavel_tecnico',
        ),
    ]
