# Generated by Django 4.2.1 on 2023-05-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_alter_responsaveltecnico_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diagnostico',
            table=None,
        ),
    ]
